# Source: cluster-api-aws/templates/job-check.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: d2226fbc-676c-4833-81fa-c9539c6066cd-capi-aws-check
  namespace: d2226fbc-676c-4833-81fa-c9539c6066cd
spec:
  template:
    metadata:
      name: d2226fbc-676c-4833-81fa-c9539c6066cd-capi-aws
    spec:
      serviceAccountName: d2226fbc-676c-4833-81fa-c9539c6066cd-capi-aws
      containers:
      - name: wait-for-ready
        image: "ghcr.io/openinfradev/python_kubectl_argo:v1.1.0"
        imagePullPolicy: IfNotPresent
        command:
        - timeout 
        - 5m
        - /wait_for_kubeconfig.sh  
        - d2226fbc-676c-4833-81fa-c9539c6066cd
        - d2226fbc-676c-4833-81fa-c9539c6066cd
        volumeMounts:
        - name: vol
          subPath: wait_for_kubeconfig.sh
          mountPath: /wait_for_kubeconfig.sh
      volumes:
      - name: vol
        configMap:
          name: d2226fbc-676c-4833-81fa-c9539c6066cd-capi-aws
          defaultMode: 0555
      restartPolicy: OnFailure
