---
apiVersion: v1
kind: Namespace
metadata:
  name: d2226fbc-676c-4833-81fa-c9539c6066cd
  labels:
    name: d2226fbc-676c-4833-81fa-c9539c6066cd
    # It bring the secret 'dacapod-argocd-config' using kubed
    decapod-argocd-config: enabled

