# Source: cluster-api-aws/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: d2226fbc-676c-4833-81fa-c9539c6066cd-capi-aws
  namespace: d2226fbc-676c-4833-81fa-c9539c6066cd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: d2226fbc-676c-4833-81fa-c9539c6066cd-capi-aws
subjects:
- kind: ServiceAccount
  name: d2226fbc-676c-4833-81fa-c9539c6066cd-capi-aws
